### ISSUE TITLE
docker_build.sh not found error, einhver með lausn?

### ISSUE THREAD

**Issue by ragnarr18** [hgop/syllabus-2019#12]
+ ./scripts/docker_build.sh 10b6d14022ffaee9984a42bb9b1294dc8e62fa3f
/var/lib/jenkins/workspace/Jenkinson2@tmp/durable-1e2bdea6/script.sh: 1: /var/lib/jenkins/workspace/Jenkinson2@tmp/durable-1e2bdea6/script.sh: ./scripts/docker_build.sh: not found
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 127
Finished: FAILURE

**Comment by emilnewel** [comment]
Mér sýnist Jenkins ekki vera að finna docker_build.sh hjá þér í scripts/ möppunni. Ertu ekki alveg örugglega búinn að pusha því á github?

**Comment by Andrim97** [comment]
docker_build og docker_push er komið inná github

**Comment by Fanneyyy** [comment]
Geturu sent link á github repoið? Svo geturu séð alla files sem Jenkins pullar með því að fara inní projectið á Jenkins, inní buildið sem failaði og hægra megin ætti að vera option “Workspaces” og þar er folder sem inniheldur allan kóðan af git. Tjékkaðu hvort scripturnar séu þar

**Comment by ragnarr18** [comment]
linkur: https://github.com/ragnarr18/hgp_andri_ragna, ok ætlum að tjékka á Jenkins console-inu

**Comment by Fanneyyy** [comment]
> linkur: https://github.com/ragnarr18/hgp_andri_ragna, ok ætlum að tjékka á Jenkins console-inu

Það þarf að adda okkur sem collaborators (`fanneyyy`, `ironpeak` og `kthorri`)

**Comment by IronPeak** [comment]
prófaðu að bæta við setningu fyrir ofan callið í docker_build.sh
`pwd`
mappan scripts ekki til staðar í directory-inu sem jenkins er staðsett í
gæti verið að þú hafir cd að yfir í game_api til þess að gera npm install?
