### ISSUE TITLE
Day 7, Unit tests order?

### ISSUE THREAD

**Issue by HjorturJ** [hgop/syllabus-2019#13]
Hversu ströng erum við að fara vera með AAA?
Er t.d. í lagi að hafa expect()... svo breyta stöðunni einhvernegin og svo aftur expect()?
Semsagt Arrange, Act, Assert, Act, Assert etc etc.
Eða er hefðin að skipta þannig hlutum uppí sér föll þótt það gæti í raun bara verið 2-3 línur sem breytast með öllu sama setupinu?

**Comment by IronPeak** [comment]
Það er í lagi í hófi. Reyna að hafa flest testinn AAA en það auðvitað mörg tilfelli (~20%) þar sem það hentar betur að gera þetta öðruvísi.

Skiptir mestu máli að testinn séu sem lesanlegust.

**Comment by HjorturJ** [comment]
Takk
