### ISSUE TITLE
Permission denied á docker_build.sh

### ISSUE THREAD

**Issue by BKarason** [hgop/syllabus-2019#16]
Ég fæ skrýtna permission denied villu á docker build scriptuna þegar ég reyni að builda á jenkins, hvernig leysi ég þetta? 

+ ./scripts/docker_build.sh fa7282e83b27c9f5eb3d3d2d318bb64872ef3776
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=jbz8d3sclclq1fsjvsgqrl003&shmsize=0&t=bkarason%2Fhgop%3Afa7282e83b27c9f5eb3d3d2d318bb64872ef3776&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

**Comment by Fanneyyy** [comment]
Hér er þráður með sama vandamáli https://stackoverflow.com/questions/44444099/how-to-solve-docker-permission-error-when-trigger-by-jenkins
