### ISSUE TITLE
Villa í gerð unit-test

### ISSUE THREAD

**Issue by ragnarr18** [hgop/syllabus-2019#17]
![image](https://user-images.githubusercontent.com/42973395/70086890-2fc34880-160b-11ea-9c62-b22061b9b85e.png)

**Comment by ragnarr18** [comment]
hvernig fór fólk framhjá því að kalla á package.json án þess að hafa hana í root
(s.s að hafa hana í staðinn í game_api folderinu)

**Comment by emilnewel** [comment]
Þú átt að hafa package.json file'inn í GameAPI möppunni og keyra bæði `npm install` og testin þar inni.

**Comment by ragnarr18** [comment]
THANK.... YOU!
