### ISSUE TITLE
Jenkins_Deploy vandræði

### ISSUE THREAD

**Issue by boddi7** [hgop/syllabus-2019#18]
Heil og sæl,

Skriftan **jenkins_deploy.sh** keyrir eftirfarandi:

ssh -o StrictHostKeyChecking=no -i "~/.aws/GameKeyPair.pem" ubuntu@$(terraform output public_ip) "./initialize_game_api_instance.sh"

Þegar hún reynir að keyra þetta á þjóninum sem varð til í AWS kemur upp eftirfarandi villa í Jenkins:

> Package docker-ce is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

> E: Package 'docker-ce' has no installation candidate
> E: Unable to locate package docker-ce-cli
> E: Unable to locate package containerd.io
> E: Couldn't find any package by glob 'containerd.io'
> E: Couldn't find any package by regex 'containerd.io'
> usermod: group 'docker' does not exist

> Couldn't connect to Docker daemon. You might need to install Docker:
> 
> https://docs.docker.com/engine/installation/

Það er eins og að skriftan sé ekki að setja Docker upp á vélinni. 

Skriftan (initialize_game_api_instance.sh) er frá ykkur og lýtur svona út:

```
#!/bin/bash

echo 'This script installs everything needed to run our API on the instance'
echo 'and then starts the API.'

echo 'Installing Docker'
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io
sudo usermod -aG docker ubuntu

echo 'Install Docker Compose'
sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

# TODO exit 1 if there is no docker-compose.yml file present.

echo 'Starting the API'
sudo docker-compose up -d
```
Gæti verið að þessi skrifta sé ekki að virka sem skyldi?

**Comment by Fanneyyy** [comment]
Ertu til í að prófa þessa uppfærðu útgáfu af scriptunni https://github.com/hgop/week1-solution-2019/blob/master/scripts/initialize_game_api_instance.sh

**Comment by boddi7** [comment]
Sæl Fanney,

Prófaði þetta með uppfærðu útgáfunni og þetta ,,stallar", þ.e. hengur þar sem það kemur interactive prompt þrátt fyrir að það sé tilgreint að það eigi ekki að gerast.

> There are services installed on your system which need to be restarted when 
> certain libraries, such as libpam, libc, and libssl, are upgraded. Since these 
> restarts may cause interruptions of service for the system, you will normally be
> prompted on each upgrade for the list of services you wish to restart.  You can 
> choose this option to avoid being prompted; instead, all necessary restarts will
> be done for you automatically so you can avoid being asked questions on each 
> library upgrade.

**Comment by IronPeak** [comment]
en ef þú prófar að gera
`sudo apt update -y`

**Comment by boddi7** [comment]
> en ef þú prófar að gera
> `sudo apt update -y`

Hengur ennþá.

**Comment by IronPeak** [comment]
kíkjum á þetta í dæmatíma

**Comment by IronPeak** [comment]
endilega fiktaðu þig áfram, ættir ekki að geta skemmt neitt með því að breyta bara þessu scripti

**Comment by Lobos98** [comment]
Við Thelma vorum í þessu í gær - lausnin okkar var að keyra línurnar `curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
sudo apt-get update
sudo apt-get install -y docker-ce docker-ce-cli containerd.io
sudo usermod -aG docker ubuntu`

tvisvar sinnum. Þessar línur virka þegar ég paste-a þeim beint inn í nýtt aws instance en þegar Jenkins hendir þeim í nýtt aws instance þá þarf að keyra þær tvisvar. Ég veit ekkert af hverju.

**Comment by HjorturJ** [comment]
#!/bin/bash

echo 'This script installs everything needed to run our API on the instance'
echo 'and then starts the API.'

echo 'Installing Docker'
sudo DEBIAN_FRONTEND=noninteractive apt-get -y update
sudo DEBIAN_FRONTEND=noninteractive apt-get -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
sudo DEBIAN_FRONTEND=noninteractive apt-get -y update
sudo DEBIAN_FRONTEND=noninteractive apt-get -y install docker-ce docker-ce-cli containerd.io
sudo usermod -aG docker ubuntu

echo 'Install Docker Compose'
sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

# Check if docker-compose.yml file is present or not.
if [ ! -f ./docker-compose.yml ]; then
    echo "docker-compose.yml file is not present"
    exit 1
fi

**Comment by HjorturJ** [comment]
Án DEBIAN_FRONTEND=noninteractive þá er console-ið að reyna prompta okkur um að fá að restarta services þrátt fyrir -y flaggann, eða þannig skildi ég þetta allavega

**Comment by IronPeak** [comment]
You can copy the script from HjorturJ (it won't affect your grade)
