### ISSUE TITLE
Warning: React version not specified in eslint-plugin-react settings.

### ISSUE THREAD

**Issue by ragnarr18** [hgop/syllabus-2019#19]
Einhver búinn að lenda í þessu í lint-ing? 
edit: þetta er apparently algengt warning

**Comment by emilnewel** [comment]
Þú getur bætt þessu við neðst í `.eslintrc.json` skrána þína: 

```
"settings": {
    "react": {
        "version": "latest"
    }
}
```

Ættir samt ekki að hugsa um þetta sem 'villu'.
