### ISSUE TITLE
Jenkins fastur á þessu þrepi í góðar 5 min núna

### ISSUE THREAD

**Issue by emilnewel** [hgop/syllabus-2019#20]
Hellu, mig minnir að ég hafi heyrt einhverja tala um það að Jenkins væri bara að chilla hjá þeim, en er ekki viss um hvort að það hafi verið einmitt á þessu skrefi. Er einhver með lausn? :)

<img width="785" alt="Screenshot 2019-12-05 at 17 03 17" src="https://user-images.githubusercontent.com/31038044/70256884-34aa0880-1781-11ea-86b1-5cffe977595d.png">

**Comment by magnuss17** [comment]
abortuðum eftir 26 mínútur og núna þegar við buildum kemur þessi villa :
![image](https://user-images.githubusercontent.com/46568875/70258739-a6378600-1784-11ea-9768-4890d2183b07.png)

**Comment by emilnewel** [comment]
Þetta var credentials mál.. :)
