### ISSUE TITLE
Sein skil

### ISSUE THREAD

**Issue by afk0901** [hgop/syllabus-2019#24]
Hvernig er seinum skilum háttað í þessum áfanga? Má skila eitthvað seinna en á miðnætti s.s. pusha inn á git eftir það? Eða verða þau commit ekki tekin gild þegar farið er yfir verkefnið?

**Comment by IronPeak** [comment]
taktu það fram í readme-inu afhverju þú þurftir lengri tíma.
við tökum mögulega tillit til þess

**Comment by IronPeak** [comment]
passaðu bara að þetta sé allavega up and running fyrir 13 á morgun, byrjum að fara yfir þetta þá
