### ISSUE TITLE
Docker-compose up

### ISSUE THREAD

**Issue by ragnarr18** [hgop/syllabus-2019#26]
úr verkefnalýsingu: Try starting your API using docker-compose locally and running your API tests:
                               API_URL=http://localhost:3000 npm run test:capacity
1. hvernig fær maður api-ið til að run-a locally
2. við fáum þessa villu þegar við keyrum docker-compose up
![image](https://user-images.githubusercontent.com/42973395/70457435-0fcad380-1aa8-11ea-9c0a-16e0db79f9ec.png)
Aðstöð að öllu tagi vel þegin!

**Comment by Olafssen** [comment]
![image](https://user-images.githubusercontent.com/34026691/70461268-2ffe9080-1ab0-11ea-836c-7df8c321f620.png)

stillir git commit breytuna sjálfur
