### ISSUE TITLE
Build time í Jenkins pipeline

### ISSUE THREAD

**Issue by kristoferg17** [hgop/syllabus-2019#28]
Hvað telst vera eðlilegur build tími fyrir API test og Capacity test í Jenkins pipeline-inu? Finnst hafa hægt ansi mikið á buildinu eftir nýju testin.

**Comment by IronPeak** [comment]
eðlilegt að þetta taki 10-15 min, þess vegna mikilvægt að þið kunnið að keyra þetta upp locally á meðan þið eruð að vinna í þessu, þar sem það er mun hraðari feedback loop.
