### ISSUE TITLE
Repository not found.

### ISSUE THREAD

**Issue by boddi7** [hgop/syllabus-2019#29]
Það þarf að græja þetta svo að við getum klárað verkefni dagsins:

> bodvar@ubuntu:~/Desktop/GIT/hgop/game-client$ git pull git@github.com:hgop/lucky-21-frontend.git
> ERROR: Repository not found.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

**Comment by IronPeak** [comment]
gleymdum að gera það public, prófaðu núna.

**Comment by boddi7** [comment]
Virkar núna, en næsta skref gengur ekki:

> bodvar@ubuntu:~/Desktop/GIT/hgop/game-client$ yarn install
> 00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

**Comment by IronPeak** [comment]
þurfti líka að breyta Connect UI, prófaðu að refresha README-inu fyrir daginn
