### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by BKarason** [hgop/syllabus-2019#3]
Daginn, mér finnst eitt óskýrt í verkefnalýsingunni. Á checka hvort notandi skriptunnar sé á mac vél og ef svo installa brew þótt að maður sjálfur sé á t.d. ubuntu?
eða mega ubuntu notendur sleppa bara brew installationinu þar sem við erum með apt-get?

**Comment by kthorri** [comment]
Nei það er nóg að supporta ykkar stýrikerfi.
