### ISSUE TITLE
Varðandi API- og Capacitytest jobbin 

### ISSUE THREAD

**Issue by emilnewel** [hgop/syllabus-2019#30]

**Comment by emilnewel** [comment]
Við erum að reyna að átta okkur á því hvar við eigum að búa til nýtt job. Ég skil það sem þið skrifið í Day11.md þannig að við eigum að búa til nýja file'a sem sjá um að api og capacity testa, en sé ekki að nýir file'ar hafi verið  bættir við í handin template'ið. Get ég fengið eitthvað hint um hvar ég ætti að bæta þessari virkni við?

**Comment by HjorturJ** [comment]
Follow up spurning: Í Day11.md, er "Jenkins job" að meina þá bara annað stage í Jenkinsfile? (fyrir apitest og capacitytest semsagt). 

Ef ekki, hvað er verið að meina með Jenkins job? Annað Jenkins pipeline sem er sérstaklega fyrir þessi tests sem við einhvernvegin tengjum við deploy pipelineið?

**Comment by IronPeak** [comment]
Jenkins Job er bara nýtt stage í þessu tilviki (það hefur gleymst að breyta wording frá því í fyrra þegar þetta var annað Job).

Þú getur gert þetta með nýjum scriptum (er líklega auðveldast), mikilvægt samt að þau script séu að nota jenkins_deploy.sh svo þú sért með alveg eins deployment process fyrir api- og capacity-tests.

**Comment by emilnewel** [comment]
Okei, ég held að ég skilji, takk fyrir.
