### ISSUE TITLE
Að fá API_URL fyrir apitest instance

### ISSUE THREAD

**Issue by emilnewel** [hgop/syllabus-2019#31]
Við erum búnir að vera fastir í eitthvern tíma núna á því hvernig væri best að fá API_URL út úr terraform. 

Við erum búnir að prófa að store'a output'ið í breytu inni í jenkinsfile en það er ekki að virka..
```
APITEST_URL = sh (
            script: '\$(terraform output public_ip)',
            returnStdout: true
        ).trim()
``` 
 og svo nota hana með `${APITEST_URL}`

Er einhver hér sem vill deila aðferð? :)

**Comment by IronPeak** [comment]
búðu til `scripts/api_test.sh` þar sem þú kallar á `jenkins_deploy.sh` inní því scripti geturu svo gert:
`API_URL=$(cd /var/.../apitest && terraform output public_ip)`

**Comment by HjorturJ** [comment]
Hvernig getum við svo fengið aðgang að API_URL variable-inu inní Jenkinsfile eftir að runna .scripts/api_test.sh? 

Ef að við reynum að runna $("API_URL=${API_URL}:3000 npm run test:api") inní api_test.sh þá finnur sú command ekki rétta folder (game_api).

Finnst eins og við viljum rönna test:api í Jenkinsfile með dir(game_api) eins og við gerum með unit testin, en vantar bara public ip-ið frá api-test.sh þá.

**Comment by IronPeak** [comment]
gætuð gert þetta þannig öll logic-in sé inní `scripts/api_test.sh`

~~~bash
./scripts/jenkins_deploy.sh ....
API_URL=$(cd /var/.../apitest && terraform output public_ip)
cd game_api
API_URL="${API_URL}:3000" npm run test:api
~~~
