### ISSUE TITLE
Tengja API við Client í utils.js

### ISSUE THREAD

**Issue by boddi7** [hgop/syllabus-2019#33]
Heil og sæl,

Í **utils.js** fyrir client er eftirfarandi breyta:

```
// TODO: Add correct api Url
const apiUrl = "";
```

Hvernig eigum við að koma API url-inu frá API container þarna fyrir sjálfvirkt?

**Comment by Fanneyyy** [comment]
Þið þurfið að nota API_URL env variable-ið sem er sett inn í docker-compose, það ætti að vera available ef þið keyrir `API_URL=yourUrl docker-compose up`

**Comment by boddi7** [comment]
Nú erum við ekki með API_URL breytu í docker-compose.yml. Við erum með þetta í jenkins_deploy skriftunni:

```
    IP=$(terraform output public_ip)
    # run the capacity tests against the new capacitytest instance.
    API_URL=http://${IP}:3000 npm run test:capacity
```

Hvernig gætum við komið þessari breytu fyrir í docker-compose.yml ?

**Comment by IronPeak** [comment]
~~~bash
export MY_VARIABLE='my value'
docker-compose up
~~~
