### ISSUE TITLE
"Bug in the API"

### ISSUE THREAD

**Issue by Lobos98** [hgop/syllabus-2019#34]
Við leituðum og leituðum að þessu hérna:

`There is a bug in the API, when the user starts the game with 21, the game does not get stored in the database, you will need to fix it.`

En fundum ekkert og breyttum engu. Við keyrðum svo 10.000 prófanir og það kom bara allt í gagnagrunnninn... Getur þetta verið?

```
curl -X GET localhost:3000/stats
{"totalNumberOfGames":10000,"totalNumberOfWins":4437,"totalNumberOf21":1051}

```

**Comment by IronPeak** [comment]
Það er mjög skrítið.

**Comment by IronPeak** [comment]
Commentaðu linkinn á repo-ið svo ég geti skoðað.

**Comment by Lobos98** [comment]
https://github.com/thelmao18/hgop-verklegt

**Comment by IronPeak** [comment]
Það er galli í lucky21 implementation-inu hjá ykkur

**Comment by IronPeak** [comment]
prófið að taka test-in sem er í week2 solution-inu og bæta þeim við í projectið ykkar.

held það muni hjálpa ykkur :)
