### ISSUE TITLE
 connect ECONNREFUSED eftir migrations? (Tests virka locally og routes virka með curl, virkar bara ekki í jest skipuninni)

### ISSUE THREAD

**Issue by HjorturJ** [hgop/syllabus-2019#35]
Ég og nokkrir aðrir hópar sem ég veit um erum allt í einu að fá þessa villu þegar við runnum api-test-in okkar eftir að við náðum að bæta við migrations.

Virkar að runna tests locally, og að directly nota curl 52.87.87.120:3000/status og start og allt.

En fáum samt þetta:

~~~
FAIL ./server.api-test.js
  ✕ play a game (13ms)

  ● play a game

    connect ECONNREFUSED 52.87.87.120:3000
~~~

**Comment by HjorturJ** [comment]
Gæti þetta mögulega verið tengt því að við erum að npm installa bara --production í dockerfile-inum okkar fyrir game_api? 

Þá skil ég samt ekki afhverju þetta myndi hafa virkað áður...

Samkvæmt npm logs á jenkins vélinni eru test:api scriptið ekki að runna neitt:

~~~
9 verbose lifecycle hgop-hj-gugg@1.0.0~test:api: CWD: /var/lib/jenkins/workspace/JenkinsHgop/game_api
10 silly lifecycle hgop-hj-gugg@1.0.0~test:api: Args: [ '-c', 'jest --testRegex *.api-test.js --collectCoverage true' ]
11 silly lifecycle hgop-hj-gugg@1.0.0~test:api: Returned: code: 1  signal: null
12 info lifecycle hgop-hj-gugg@1.0.0~test:api: Failed to exec test:api script
13 verbose stack Error: hgop-hj-gugg@1.0.0 test:api: `jest --testRegex *.api-test.js --collectCoverage true`
13 verbose stack Exit status 1
~~~

**Comment by boddi7** [comment]
Við vorum að lenda í þessu vegna þess að það var verið að sleep-a í Dockerfile:

> CMD sleep 5 && npm run migratedb:pg && node app.js

Fjarlægðum sleep og þetta virkaði.

**Comment by HjorturJ** [comment]
Breytti engu hjá mér :(

**Comment by emilnewel** [comment]
Ekki heldur hjá okkur, @boddi7 ertu viss um að þið breyttuð engu öðru í leiðinni?

**Comment by boddi7** [comment]
Þetta var allavegana það helsta sem ég man eftir. Voruð þið annars ekki búnir að skoða uppfærða readme skjalið fyrir daginn?

**Access-Control-Allow-Origin Header**

```
  app.use((req, res, next) => {
    res.header("Access-Control-Allow-Origin", "*");
    next();
  });
```
**Game Client**

```
  game_client:
    image: username/game_client:${GIT_COMMIT}
    ports:
    - '4000:4000'
    depends_on:
    - game_api
    environment:
      PORT: 4000
      API_PORT: 3000
      API_URL: ${API_URL}
```

**Comment by HjorturJ** [comment]
Jújú, búin að skoða update README, og kominn með allt sem er í því inní projectið. Allt runnar locally og líka GameServer_apitest instance-ið er að svara curl skipunum.

Bara Jest skipunin sem runnar apitests er ekki að connecta, þótt instance-ið sem það á að connecta við sé að taka við requests.

**Comment by emilnewel** [comment]
Er þetta ekki partur af UI'inu samt, @boddi7 ? Ég myndi halda að það tengist ekki gagnagrunninum... 🤷‍♂

**Comment by IronPeak** [comment]
prófiði að sleepa í 20 sec á meðan instance-ið er að fara í gang og svo runna api tests

**Comment by HjorturJ** [comment]
Gerist það sama, með sleep 10, 20 og 30, hingað til :)

**Comment by IronPeak** [comment]
prófaðu að bæta http:// fyrir fram ip töluna

**Comment by HjorturJ** [comment]
~~~
API_URL=http://${API_IP}:3000 npm run test:api
~~~
Væri það ekki þessi lína?

**Comment by IronPeak** [comment]
settir sleep á rangan stað ;)
ætti að vera:
~~~bash
#!/bin/bash

API_IP=$(cd /var/lib/jenkins/terraform/hgop/apitest && terraform output public_ip)

echo $API_IP
sleep 15
API_URL=http://${API_IP}:3000 npm run test:api
~~~

**Comment by IronPeak** [comment]
taktu sleepið útúr dockerfile-num það gerir þetta vandamál enþá verra :)

**Comment by HjorturJ** [comment]
Hahaha ok, skal prófa

**Comment by IronPeak** [comment]
bara hafa 5 sec þar til þess að vera viss um að postgres containerinn sé ready to accept connections áður en migrations eru keyrðar.

**Comment by guggaivans** [comment]
<img width="580" alt="Screenshot 2019-12-10 at 21 59 17" src="https://user-images.githubusercontent.com/34030076/70572784-66173f80-1b98-11ea-8840-05ed8d62276d.png">


Takk Hrafn!
