### ISSUE TITLE
docker-compose up vandræði

### ISSUE THREAD

**Issue by koffa95** [hgop/syllabus-2019#36]
![image](https://user-images.githubusercontent.com/35893828/70561144-d8305a00-1b81-11ea-9f02-f26e0221a831.png)

Ég er að reyna að keyra docker-compose up til þess að testa kóðann locally og fæ alltaf þessa villu upp. Veit einhver hvað er í gangi?

**Comment by emilnewel** [comment]
Docker er ekki að finna context.js skrána hjá þér. Ertu ekki alveg örugglega að COPY'a allar skrár sem enda á .js? 

Það væri þá skipunin `COPY *.js ./` í Dockerfile'num ykkar.

**Comment by koffa95** [comment]
Takk kærlega :+1: það var eitt stykki stafsetningavilla í línunni hjá mér sem ég sá ekki.
