### ISSUE TITLE
Útlit á Client ekki að virka sem skyldi

### ISSUE THREAD

**Issue by boddi7** [hgop/syllabus-2019#37]
Þegar ég keyri þetta locally og út á við ( http://54.211.93.243:4000/ ) fæ ég þetta frekar brenglað í útliti. 

Eru fleiri að lenda í þessu eða er ég einn að lenda í þessu? Öll tips velkomin.

**Comment by Fanneyyy** [comment]
Geturu sent screenshot?

**Comment by Fanneyyy** [comment]
Æji eru þetta svg?

**Comment by Fanneyyy** [comment]
Hver er error í console? Cross origin?

**Comment by boddi7** [comment]
![image](https://user-images.githubusercontent.com/5121180/70569073-1d0fbd00-1b91-11ea-85b4-94a036c089fc.png)

Svona kemur þetta út hjá mér.

**Comment by HjorturJ** [comment]
Þetta er líka svona hjá okkur :)

![image](https://user-images.githubusercontent.com/34068269/70569352-b17a1f80-1b91-11ea-8055-05695ed20d4c.png)

**Comment by Fanneyyy** [comment]
Það ætti ekki að vera koma error tengdur localhost, er einhverstaðar hardcoded localhost í einhverju sem þið eruð að keyra á jenkins?

**Comment by boddi7** [comment]
Localhost kemur eingöngu fyrir í start_local.sh hjá mér:
![image](https://user-images.githubusercontent.com/5121180/70569599-28171d00-1b92-11ea-86c1-437066f16e33.png)

Þetta er því eitthvað annað sem er að valda þessu.

**Comment by HjorturJ** [comment]
Sama hér, eini staðurinn sem localhost er skrifað í öllu projectinu er í scriptunni sem við fengum frá Hrafni.

**Comment by IronPeak** [comment]
eru þið að nota `start_local.sh` sem var gefið í hints, lýtur út eins og þið séuð ekki að builda game_client-inn

**Comment by HjorturJ** [comment]
~~~
#!/bin/bash

set -euxo pipefail

docker build game_api -t hjorturj/game_api:dev
(cd game_client && npm build)
docker build game_client -t hjorturj/game_client:dev

API_URL=localhost GIT_COMMIT=dev docker-compose up
~~~

Þetta er hvernig ég breytti start_local.sh, og er að nota það, sést eitthvað áhugavert við þetta?

**Comment by boddi7** [comment]
> eru þið að nota `start_local.sh` sem var gefið í hints, lýtur út eins og þið séuð ekki að builda game_client-inn

Ég er að builda þetta og þú getur séð þetta hér: http://54.211.93.243:4000/

**Comment by IronPeak** [comment]
silly me, it's supposed to be `npm run build` :man_facepalming:

**Comment by IronPeak** [comment]
uppfærði hints fyrir day 12

**Comment by boddi7** [comment]
> uppfærði hints fyrir day 12

Þetta virkaði fyrir start_local en mig grunar þó að það sé eitthvað að Dockerfile skránni fyrir game-client:

```
FROM node:latest

WORKDIR /code
COPY package.json package.json
RUN npm install
COPY . .
CMD ["npm", "start"]
```
Vantar ekkert þarna inn? Ætti ekki að vera npm run build?
