### ISSUE TITLE
Vandræði með metrics í Datadog

### ISSUE THREAD

**Issue by boddi7** [hgop/syllabus-2019#39]
Heil og sæl,

Er í vandræðum með að fá gögnin/metrics (increment-ið) frá server.js sent til DataDog. Í server.js er ég með eftirfarandi:

```
  const StatsD = require('hot-shots');
  const client = new StatsD();
```

```
  // Starts a new game.
  app.post('/start', (req, res) => {
    if (game && game.isGameOver(game) == false) {
      res.statusCode = 409;
      res.send('There is already a game in progress');
    } else {
      game = lucky21Constructor(context);
      const msg = 'Game started';
      client.increment('game.count');
      res.statusCode = 201;
      res.send(msg);
    }
  });
```
Allt buildast og deployast eðlilega og þegar ég spila þetta svo á netinu fæ ég engin metrics send í DataDog. Hvað gæti verið að fara úrskeiðis?

Annað eins og CPU og Memory birtist eðlilega.

**Comment by IronPeak** [comment]
vantar host parameter í new StatsD()

**Comment by IronPeak** [comment]
~~~javascript
const client = new StatsD(
    host: "your datadog container",
);
~~~

**Comment by boddi7** [comment]
Sælir

Reyndi að gera þetta með því að tilgreina host beint og það gekk ekki. Prófaði því næst að nota DD_AGENT án árangurs.

Tekið frá https://www.npmjs.com/package/hot-shots

> host: The host to send stats to, if not set, the constructor tries to retrieve it from the DD_AGENT_HOST environment variable, default: localhost

Í docker-compose.yml er ég með eftirfarandi:

`DD_AGENT_HOST: ${IP}`

Sem fær þetta frá docker_compose_up.sh:

`export IP=$4`

sem fær þetta frá jenkins_deploy.sh:

```
initAndCompose () {
    ssh -o StrictHostKeyChecking=no -i "~/.aws/GameKeyPair.pem" ubuntu@$(terraform output public_ip) "./initialize_game_api_instance.sh"
    ssh -o StrictHostKeyChecking=no -i "~/.aws/GameKeyPair.pem" ubuntu@$(terraform output public_ip) "./docker_compose_up.sh $GIT_COMMIT http://$IP $ENV $IP"
}
```

IP talan sem send er sem parameter er á forminu: 3.89.232.13

**Comment by boddi7** [comment]
Var að prófa þetta locally og sá eftirfarandi villu:

`my_datadog_container_1   | 2019-12-13 10:34:41 UTC | PROCESS | ERROR | (collector.go:209 in postMessage) | Error submitting payload to https://process.datadoghq.eu/api/v1/container: Post https://process.datadoghq.eu/api/v1/container: x509: certificate signed by unknown authority`

Spurning hvort að þetta gæti verið orsökin?
