### ISSUE TITLE
[A1] Á að geta runnað script-una án sudo? 

### ISSUE THREAD

**Issue by emilnewel** [hgop/syllabus-2019#4]
Þar sem að fólk á linux er að notast við apt-get þá geri ég ráð fyrir því að það þurfi sudo réttindi á vélinni til þess að geta runnað. Eigum við að gera ráð fyrir því að manneskjan sem runnar sé með þau réttindi?

**Comment by Fanneyyy** [comment]
Þessi scripta er ætluð fyrir persónulega uppsetningu þannig já má klárlega gera ráð fyrir að notandi sé með sudo réttindi. Fyrir linux væri sniðugast að hafa sudo fyrir framan þær skipanir sem þurfa á því að halda, eins og apt-get þannig að hún faili ekki ef scripta er keyrð án sudo heldur sé beðið um password ef þess þarf. Meikar sense?

**Comment by emilnewel** [comment]
Meikar fullkominn sense, takk. 😄
