### ISSUE TITLE
ECONNECTREFUSE á Jenkins og skrítin villa locally eftir db-migration

### ISSUE THREAD

**Issue by koffa95** [hgop/syllabus-2019#40]
![image](https://user-images.githubusercontent.com/35893828/70675151-45c2b000-1c80-11ea-82b2-dda5e7f23e3d.png)
Fæ þetta við að keyra locally. Hann fann einnig ekki ./context.js af einhverjum ástæðum þrátt fyrir að COPY *.js /. væri í Dockerfile þannig ég bætti śer copy skipun inn fyrir það.

![image](https://user-images.githubusercontent.com/35893828/70675266-a356fc80-1c80-11ea-98ac-3b4c30e341df.png)
Fæ þetta frá Jenkins. Er búin að prófa að taka sleep úr Dockerfile, og passaði að það sé á réttum stað í api_sleep.sh miðað við svörin á hinu issue-inu hér inni. Veit einhver hvað er í gangi?

**Comment by IronPeak** [comment]
database.json þarf að connecta við réttan host.

**Comment by koffa95** [comment]
Ég skil ekki alveg hvar við erum að gera eitthvað vitlaust? Geturu gefið okkur hint?

**Comment by IronPeak** [comment]
migration-in eru að nota database.json configuration-in til þess að reyna að connecta við postgres, eru þau configurations rétt?
