### ISSUE TITLE
Build stage á Pipelineinu failar þegar það reynir að builda game_client

### ISSUE THREAD

**Issue by BKarason** [hgop/syllabus-2019#41]
Ég fæ þetta í hvert skipti sem ég builda eftir að ég bætti við game_client og ég er búinn að reyna allt og skil ekki hvað er að, hjálp

> lucky-21-frontend@1.0.0 build /var/lib/jenkins/workspace/HGOP-Birkir/game_client
> cp -R cards dist && parcel build ./src/index.html --public-url ./

sh: 1: parcel: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! lucky-21-frontend@1.0.0 build: `cp -R cards dist && parcel build ./src/index.html --public-url ./`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the lucky-21-frontend@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/lib/jenkins/.npm/_logs/2019-12-12T14_06_01_842Z-debug.log
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE

**Comment by IronPeak** [comment]
búinn að gera npm install inní game_client

p.s. passa að læra undir lokaprófið

**Comment by BKarason** [comment]
Já ég gerði npm install, svo er "RUN npm install" í Dockerfælnum

**Comment by IronPeak** [comment]
væri best að gera npm install í setup skrefinu fyrir bæði client og api.

**Comment by BKarason** [comment]
já vá, ég steingleymdi að bæta við client þar, takk fyrir
