### ISSUE TITLE
ECONNECTREFUSE

### ISSUE THREAD

**Issue by einaroddurpall** [hgop/syllabus-2019#42]
Við fáum ECONNECTREFUSE á API testin þrátt fyrir að vera með sleep á réttum stað og við náum að keyra locally og leikurinn virkar þar.
Þetta virkaði allt saman áður en við gerðum DataDog, eftir það byrjaði þetta að klikka.

**Comment by OlafurBJonsson** [comment]
Við erum líka að lenda í þessu. Það virkaði allt hjá okkur líka þar til að við gerðum DataDog.

**Comment by OlafurBJonsson** [comment]
Það sem við gerðum til að laga var að taka úr error handlerinn þar sem við vorum ekki búnir að define-a hann. Mikilvægt að þetta er beint fyrir neðan app.use skipunina.
`  const client = new StatsD({
    host: 'my_datadog_container',
    globalTags: { env: process.env.NODE_ENV }
  });`
