### ISSUE TITLE
tests og UI ekki að virka

### ISSUE THREAD

**Issue by ragnarr18** [hgop/syllabus-2019#43]
erum að reyna keyra capacity test en gefa mjög skrítna villu
![image](https://user-images.githubusercontent.com/42973395/70822585-ccd56c80-1dd5-11ea-9c20-90ac5c2ec046.png)

þar að auki erum við að reyna spila leikinn locally
en fáum bara þetta í byrjun leiksins
![image](https://user-images.githubusercontent.com/42973395/70822667-060ddc80-1dd6-11ea-9a41-659745c88f8c.png)

ef einhver getur gefið ráð eða hjálpað væri awesome, peace out

**Comment by Fanneyyy** [comment]
Lítur út eins og UIið sé ekki með rétt URL á APIinn, eruð þið búnir að bæta API_URL í game_client projectið?

**Comment by ragnarr18** [comment]
já :/

**Comment by ragnarr18** [comment]
er þetta eðlilegt þegar maður runnar leikinn locally?
![image](https://user-images.githubusercontent.com/42973395/70824862-09f02d80-1ddb-11ea-93fa-c5b820bb0e4a.png)

**Comment by ragnarr18** [comment]
anybody?

**Comment by IronPeak** [comment]
Þú þarf að láta capacity prófin fá API_URL, þú er að skoða clientinn
API_URL=localhost:3000 npm run test:capacity

**Comment by IronPeak** [comment]
þá ertu að declare-a API_URL environment sem capacity testin nota til þess að connecta við API-ið og spila leik.

**Comment by ragnarr18** [comment]
gekk ekki upp
erum núna að reyna að keyra testin án clients 
það gengur illa

**Comment by IronPeak** [comment]
skoðaðu start localhost og settu inn API_URL eins og þið eruð að setja inn GIT_COMMIT

startaðu keyrðu ./scripts/start_local.sh

í öðrum terminal:
cd game_api
API_URL=http://localhost:3000 npm run test:capacity

**Comment by ragnarr18** [comment]
settu inn API-URL eins og setja inn GIT-COMMIT, nú er ég ekki að botna í þér

**Comment by ragnarr18** [comment]
![image](https://user-images.githubusercontent.com/42973395/70832728-c4892b80-1ded-11ea-99d1-bcf002aca85c.png)
this is what I've got so far

**Comment by Fanneyyy** [comment]
Lítur út eins og env variable-ið sé eitthvað skrýtið, það má ekki vera bil `API_URL= http` og það vantar `:` í urlið

**Comment by ragnarr18** [comment]
ok lagaði url-ið og fæ eftirfarandi
(:
![image](https://user-images.githubusercontent.com/42973395/70835298-86433a80-1df4-11ea-8381-6589024fb759.png)

**Comment by IronPeak** [comment]
testið hjá þér er að connecta við client-inn en það á að tala við api-ið
passaðu að API_URL-ið sem testið er að nota sé :3000 og að game_api sé að hlusta á porti 3000

**Comment by ragnarr18** [comment]
takk fyrir hjálpina en þetta bara gengur ekki upp, komið gott í bili
