### ISSUE TITLE
Client loadast ekki almennilega

### ISSUE THREAD

**Issue by ElinVilbergs** [hgop/syllabus-2019#44]
![image](https://user-images.githubusercontent.com/34030656/70829827-96ecb400-1de6-11ea-86a0-3910243011ae.png)
Clientinn fer ekki lengra en þetta. Allir TO-DO's í src eru komnir og API path. 
Hjálp?

**Comment by IronPeak** [comment]
gerðu console.log(apiUrl)
í game_client/src/utils.js

**Comment by Fanneyyy** [comment]
Eruð þið kannski að setja inn vitlaust port? game_api keyrir á 3000 ekki 4000

**Comment by ElinVilbergs** [comment]
Þetta er komið í lag en það virkar bara á :4000
:3000 gefur bara Cannot GET /start
