### ISSUE TITLE
Bash scripta sem styður tvö stýrikerfi

### ISSUE THREAD

**Issue by kristjaningi** [hgop/syllabus-2019#5]
Ef annar aðilinn í hópnum er á öðru stýrikerfi (t.d. Mac + Ubuntu). Hvort erum við að fara henda í eina scriptu með OS checki eða tvær mismunandi scriptur?

**Comment by emilnewel** [comment]
Ég og hópmeðlimurinn minn fengum þær upplýsingar að það væri í lagi að gera tvær scriptur.

**Comment by kthorri** [comment]
@kristjaningi þú ert velkominn til að mæta í dæmatíma :)
