### ISSUE TITLE
Búa til key pair fyrir AWS

### ISSUE THREAD

**Issue by gabriels17** [hgop/syllabus-2019#7]
Er í vandræðum að búa til nýtt key pair á aws, ég fæ alltaf þessi skilaboð: 
You are not authorized to perform this operation.

Veit einhver hvað er að og hvernig á að leysa þetta?

**Comment by kthorri** [comment]
Erfitt að segja,
gott væri að skoða þetta í dæmatímanum á morgun ef leiðbeiningum af degi 3 var fylgt.
